# Generated by Django 3.2.6 on 2021-08-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
